### ISSUE TITLE
Impersonating MscrmTools

### ISSUE THREAD

**Issue by rappen** [santoshCRM/RoleReplicator#1]
Plugin info states author: MscrmTools and it has his logo, but this is not from @mscrmtools.

![image](https://user-images.githubusercontent.com/2572253/27274881-5af422e4-54d5-11e7-8ed5-4ff3f9bfdf4e.png)

**Comment by mscottsewell** [comment]
Can this be blocked since it's invalid/impersonated?

**Comment by MscrmTools** [comment]
It will be possible in a (hopefully) near future where all plugins will be retrieved from the upcoming XrmToolBox portal.
For now, I cannot block it

**Comment by rappen** [comment]
And @santoshCRM does not seem to be too eager to do something about it... Ping!

**Comment by santoshCRM** [comment]
it was updated on last friday.
Now logo and author name both are changed.

**Comment by rappen** [comment]
Great!
A good tip is to associate the commit with the issue, by entering commit comment "Fixed #1" or similar. Then the reporter (me) can follow the progress of the issue.
