### ISSUE TITLE
Error message when trying to duplicate profil

### ISSUE THREAD

**Issue by AdminDRC** [santoshCRM/RoleReplicator#8]
Hello,

I enconter an issue trying to use Role replicator. Each time i try to copy roles, teams or queues (1 of them or the 3 of them) I get an error message.
You can read on the error message: An error occured: 'Queue' entity doesn't contain attribute with Name = 'msdyn_queuetype' and NameMapping = 'logical'. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=6683555693, MetadatasInsatnceId=47090664, LastUpadated=2021-07-04 06:17:15.923

I use the last version of XrmToolbox and the last version of role replicator.
I tried everything, now i'm stuck and can not achieve to copy profiles.

Can you help me to solve this issue?

Thnak you in advance for youre help.

Florian.
<img width="961" alt="XRM" src="https://user-images.githubusercontent.com/86964558/124472009-e5351f80-dd9d-11eb-9e39-a1fbd63190ce.png">

**Comment by amanjotsingh1** [comment]
Hello Santosh, 

Hope you doing good. 

I am still getting this same error as above when trying to run the copy. Tried with different environments as well as different users still receive the same error also tried different versions of XRMToolbox. 

Please help.

Thank you 
Aman

**Comment by LinkeD365** [comment]
Unfortunately, this is a side project we do for free for @santoshCRM and I. I am not sure when this will be resolved.

**Comment by santoshCRM** [comment]
Hi @amanjotsingh1 and @AdminDRC ,
It seems like "msdyn_queuetype" attributes removed from queue in your version on CRM.
can you update which CRM version you are using and can also try below web api query and share new name of attribute.
I tried with trail crm and it's working fine. 

https://**YourCRMURL/api/data/v9.2**/systemusers?$select=fullname,systemuserid&$expand=systemuserroles_association($select=name,roleid),teammembership_association($select=teamid,name),queuemembership_association($select=queuetypecode,queueid,name,msdyn_queuetype;$filter=(queueviewtype eq 1 and not contains(name, '%3c')))&$filter=(queuemembership_association/any(o1:(o1/queueviewtype eq 1 and not contains(o1%2fname, '%3c'))))

**Comment by amanjotsingh1** [comment]
Hello @santoshCRM,

Thank you for your prompt response. 

CRM version is:

Microsoft Dynamics 365

2021 release wave 1 enabled
Server version: 9.2.21062.00128
Client version: 1.4.2823-2106.2


![image](https://user-images.githubusercontent.com/87116452/124901425-5b978300-e025-11eb-9bcd-da49d44818ae.png)

**Comment by santoshCRM** [comment]
@amanjotsingh1 ,
 Can you try below:
replacing msdyn_queuetype with queuetype

https://YourCRMURL/api/data/v9.2/systemusers?$select=fullname,systemuserid&$expand=systemuserroles_association($select=name,roleid),teammembership_association($select=teamid,name),queuemembership_association($select=queuetypecode,queueid,name,queuetype;$filter=(queueviewtype eq 1 and not contains(name, '%3c')))&$filter=(queuemembership_association/any(o1:(o1/queueviewtype eq 1 and not contains(o1%2fname, '%3c'))))

**Comment by amanjotsingh1** [comment]
@santoshCRM I got the same response as above with queuetype, however, I had a look at the queue entity and found the attribute/field call queueviewtype and got a big response with a list of users. e.g:

![image](https://user-images.githubusercontent.com/87116452/124903258-268c3000-e027-11eb-9463-1a90b6b4c1ad.png)

and if I switch to the Response Body tab then it gives details of a user - which teams, roles, and queues he/she is in. 

as the issue we experiencing is with queue entity, i have taken the below screen capture. 

![image](https://user-images.githubusercontent.com/87116452/124904009-e7121380-e027-11eb-8465-c3b823bfcf60.png)

Let me know if you need some other information from the response.

**Comment by santoshCRM** [comment]
Issue resolved in new version. Use 1.2021.7.8 version.

**Comment by amanjotsingh1** [comment]
I’ll try it tomorrow and will provide you an update. Thank you very much for addressing the issue.

Amanjot Singh Dhaliwal
________________________________

**Comment by AdminDRC** [comment]
Hi @santoshCRM,

Thank you for your help! I confirm that it is working in the latest version.

Florian.

**Comment by amanjotsingh1** [comment]
Morning @santoshCRM, it's working for me as well. Thank you very much.
